fix: .yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,12 +1,12 @@
 name: Build and Deploy to DockerHub
 
 on:
-    push:
-      branches:
-        - main
-    pull_request:
-      branches:
-        - main
+  push:
+    branches:
+      - main
+  pull_request:
+    branches:
+      - main
 
 jobs:
   build:
@@ -42,15 +42,13 @@ jobs:
 
     - name: Add SSH host key
       run: |
-        mkdir -p ~/.ssh
         ssh-keyscan -H 201.23.3.86 >> ~/.ssh/known_hosts
 
     - name: Deploy container to remote server
       run: |
         ssh -i ~/.ssh/id_rsa aluno@201.23.3.86 "
         docker pull ${{ secrets.DOCKER_USERNAME }}/square-number-app:latest &&
-        docker stop square-number-app || true &&
-        docker rm square-number-app || true &&
+        (docker stop square-number-app || echo 'No container to stop') &&
+        (docker rm square-number-app || echo 'No container to remove') &&
         docker run -d --name square-number-app -p 8102:8080 ${{ secrets.DOCKER_USERNAME }}/square-number-app:latest
-        "
-      
+        " || echo 'Deploy failed. Check SSH or Docker setup.'
