g

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -53,16 +53,16 @@ jobs:
       run: |
         ssh -i ~/.ssh/id_rsa aluno@201.23.3.86 "
           sudo fuser -k 8102/tcp || echo 'No process found on port 8102';
-          sudo docker stop atividade || echo 'No container named atividade to stop';
-          sudo docker remote $(Docker ps -aq) --force || echo 'No container erro no force';
-          sudo docker rm atividade || echo 'No container named atividade to remove';
+          docker stop $(Docker ps -aq) || echo 'No container named atividade to stop';
+          docker remote $(Docker ps -aq) --force || echo 'No container erro no force';
+          docker rm atividade || echo 'No container named atividade to remove';
         "
 
     - name: Deploy container to remote server
       run: |
         ssh -i ~/.ssh/id_rsa aluno@201.23.3.86 "
           docker info || sudo systemctl start docker;
-          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/atividade:latest &&
-          sudo docker run -d -p 8102:8102 --name atividade ${{ secrets.DOCKER_USERNAME }}/atividade:latest;
-          sudo docker ps | grep atividade || echo 'Container failed to start';
+          docker pull ${{ secrets.DOCKER_USERNAME }}/atividade:latest &&
+          docker run -d -p 8102:8102 --name atividade ${{ secrets.DOCKER_USERNAME }}/atividade:latest;
+          docker ps | grep atividade || echo 'Container failed to start';
         "
