e

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -53,15 +53,15 @@ jobs:
       run: |
         ssh -i ~/.ssh/id_rsa aluno@201.23.3.86 "
           sudo fuser -k 8102/tcp || echo 'No process found on port 8102';
-          docker stop atividade || echo 'No container named atividade to stop';
-          docker rm atividade || echo 'No container named atividade to remove';
+          sudo docker stop atividade || echo 'No container named atividade to stop';
+          sudo docker rm atividade || echo 'No container named atividade to remove';
         "
 
     - name: Deploy container to remote server
       run: |
         ssh -i ~/.ssh/id_rsa aluno@201.23.3.86 "
           docker info || sudo systemctl start docker;
-          docker pull ${{ secrets.DOCKER_USERNAME }}/atividade:latest &&
-          docker run -d -p 8102:8080 --name atividade ${{ secrets.DOCKER_USERNAME }}/atividade:latest;
-          docker ps | grep atividade || echo 'Container failed to start';
+          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/atividade:latest &&
+          sudo docker run -d -p 8102:8102 --name atividade ${{ secrets.DOCKER_USERNAME }}/atividade:latest;
+          sudo docker ps | grep atividade || echo 'Container failed to start';
         "
